#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <signal.h>
#include <iostream>
#include <fstream>
#include <string>
#include <sstream>
#include <filesystem>
#include <vector>
#include <cstring>
#include <algorithm>
#include <set>
#include <map>
#include <tuple>
#include <ctime>
#include <ldap.h>
#include <termios.h>
#include <stdexcept>
#include <thread>
#include <mutex>